#!/bin/sh

# Usage ./gitpush.sh <file> <repo>

git init
git add $1
git commit -m "generated by gitpush.sh"
git remote add origin https://github.com/n8chz/$2.git
sudo git fetch origin
sudo git merge origin/master
sudo git push origin master

